#!/bin/python
import os
import os.path as path


base_dir = path.dirname(path.realpath(__file__))
files = {
    'bspwmrc':   '~/.config/bspwm/bspwmrc',
    'sxhkdrc':   '~/.config/sxhkd/sxhkdrc',
    'vimrc':     '~/.vimrc',
    'Xdefaults': '~/.Xdefaults',
    'xinitrc':   '~/.xinitrc',
    'zshrc':     '~/.zshrc',
    'gtkrc-2.0': '~/.gtkrc-2.0',
    'zshenv':    '~/.zshenv',
    'gdbinit':   '~/.gdbinit',
}

for source, target in files.items():
    print(source, ": ", sep='', end='')

    source_full = path.join(base_dir, source)
    target_full = path.expanduser(target)

    if path.exists(target_full):
        if path.islink(target_full):
            existing_target = os.readlink(target_full)

            if existing_target == source_full:
                print("Already linked")
                continue
            else:
                skip = input(target_full + " already exists, overwrite? [y/N] ")

                if skip == 'N' or not skip:
                    print("Skipped")
                    continue
                else:
                    os.remove(target_full)

    os.symlink(source_full, target_full)
    print("Linked")
