#!/bin/zsh

# Basic Settings
bspc config border_width        1
bspc config window_gap          5
bspc config split_ratio         0.50
bspc config borderless_monocle  true
bspc config gapless_monocle     true
bspc config focus_by_distance   true

bspc config normal_border_color  $DARK_GRAY
bspc config focused_border_color $LIGHT_GRAY
bspc config urgent_border_color  $RED

bspc monitor -d 1 2 3 4 5 6 7 8 9 10

xsetroot -solid "$DARK_GRAY"
