#!/bin/zsh

# Basic Settings
bspc config border_width        1
bspc config window_gap          5
bspc config split_ratio         0.50
bspc config borderless_monocle  true
bspc config gapless_monocle     true
bspc config click_to_focus      button1
bspc config swallow_first_click false

# Mouse Settings
bspc config pointer_modifier    mod1 # Alt
bspc config pointer_action1     move
bspc config pointer_action2     resize_corner

bspc config normal_border_color  $GREY
bspc config focused_border_color $LIGHT_GREY

bspc monitor -d 1 2 3 4 5 6 7 8 9 10

# Rules
bspc rule -a feh state=floating
bspc rule -a Thunderbird state=floating, locked=on
bspc rule -a Yad state=floating
bspc rule -a Slack state=floating
bspc rule -a Playground state=floating

xsetroot -solid "#333333"
$HOME/.config/polybar/launch.sh
