#!/bin/sh

export LD_PRELOAD="libpthread.so.0 libGL.so.1"
export __GL_THREADED_OPTIMISATIONS=1
export WINEDEBUG=-all
export WINEARCH=win32
export WINEPREFIX=/home/james/.wine/prefix32
WINE=/bin/wine

$WINE "/media/Spinpoint/Games/Heroes of the Storm/Heroes of the Storm.exe" -nohttpauth
