#!/bin/zsh

rofi -show run \
     -width 20 \
     -lines 3 \
     -bw 1 \
     -location 2 \
     -padding 0 \
     -i \
     -font "Liberation Sans 11" \
     -color-window $BLACK,$GREY,$GREY \
     -color-normal $BLACK,$WHITE,$BLACK,$BLACK,$WHITE \
     -separator-style "solid" \
     -hide-scrollbar \
     -sorting-method fzf \
     -sort
