#!/bin/zsh

. panel-settings

make_rgb() {
    echo "#${1:3}"
}

dmenu_run -w $(bc <<< "$WIDTH * 0.3") -h $HEIGHT -x $PADDING -y $PADDING \
          -p ">" -q -fn $FONT_FAMILY -i \
          -nb $(make_rgb $COLOUR_BG) -nf $(make_rgb $COLOUR_FG) \
          -sb $(make_rgb $COLOUR_BG) -sf $(make_rgb $COLOUR_HI)
