#!/bin/zsh

# Kill any existing bars
if [ $(pgrep -cx lemonbar) -gt 0 ]; then
    kill -USR1 $(pgrep -x lemonbar)
fi

# Load Settings
. panel-settings

bspc config top_padding $(($HEIGHT + $PADDING))

panel-text | \
lemonbar -g $((WIDTH))x$((HEIGHT)) -f "$FONT_1" -f "$FONT_2" \
         -F $WHITE -B $BLACK &
