#!/bin/zsh

. panel-settings

ul="%{U$COLOUR_HI!u}"

clock() {
    date +"%d/%m/%Y %H:%M"
}

desktops() {
    desktops=""

    for monitor in $(bspc query -M); do
        for desktop in $(bspc query -D -m $monitor); do
            if [[ $desktop -eq $(bspc query -D -d focused) ]]; then
                desktops+="$ul $desktop %{U-!u}"
            else
                desktops+=" $desktop "
            fi
        done
    done

    echo "$desktops"
}

while true; do
    buf=""

    # buf="$buf $(music)"
    buf+="%{c}"
    buf+="$(desktops)"
    buf+="%{r}"
    # buf+= "$buf $(apps)"
    # buf+= "$buf $green$fg $(batt)%"
    # buf+= "$buf $blue$fg $(vol)"
    buf+="$(clock) "

    echo $buf
    sleep 1
done
