#!/bin/zsh

# Kill any existing bars
if [ $(pgrep -cx bar) -gt 0 ]; then
    kill -USR1 $(pgrep -x bar)
fi

# Load Settings
. panel-settings

if [[ $(hostname) == 'pc' ]]; then
    bspc config -m DFP5 top_padding $(($HEIGHT + $PADDING))
else
    bspc config top_padding $(($HEIGHT + $PADDING))
fi

panel-text | \
bar -g $(($WIDTH - $PADDING))x$HEIGHT+$PADDING+$PADDING -f "$FONT_FAMILY" -u 3 \
    -F "$COLOUR_FG" -B "$COLOUR_BG" &
