#!/bin/zsh

read WIDTH <<< $(xrandr | grep '*' | awk -Fx '{print $1}')

FONT_FAMILY="xft:DejaVu Sans:pixelsize=11"
HEIGHT=20
PADDING=3
WIDTH=$((WIDTH - 2 * PADDING))
COLOUR_BG=${BLACK/#\#/\#FF}
COLOUR_FG=${WHITE/#\#/\#FF}
COLOUR_HI=${BLUE/#\#/\#FF}
