#!/bin/zsh

# Kill any existing bars
if [ $(pgrep -cx lemonbar) -gt 0 ]; then
    kill -USR1 $(pgrep -x lemonbar)
fi

# Load Settings
. panel-settings

bspc config top_padding $(($HEIGHT + $PADDING))

panel-text | \
lemonbar -g $(($WIDTH - $PADDING))x$HEIGHT+$PADDING+$PADDING -f "$FONT_FAMILY" \
         -u 3 -F "$COLOUR_FG" -B "$COLOUR_BG" &
