#!/bin/zsh

. panel-settings

highlight() {
    echo -n "%{F$BLUE}$@%{F-}"
}

rarrow() {
    echo -n "%{F$1 B$2}%{T2}%{T-}%{F-B-}"
}

rgroup() {
    echo -n "$(rarrow $2 $1)%{F$1 B$2} ${@:3} %{F-B-}";
}

clock() {
    rgroup $BLACK $BLUE $(date +"%H:%M  %d/%m/%Y")
}

desktops() {
    desktops=""

    for monitor in $(bspc query -M); do
        for desktop in $(bspc query -D -m $monitor); do
            if [[ $desktop -eq $(bspc query -D -d focused) ]]; then
                desktops+=$(highlight " %{T2}●%{T-} ")
            else
                desktops+=" %{T2}●%{T-} "
            fi
        done
    done

    echo "$desktops"
}

battery() {
    full=$(cat /sys/class/power_supply/BAT0/charge_full)
    curr=$(cat /sys/class/power_supply/BAT0/charge_now)

    msg=$(cat /sys/class/power_supply/BAT0/status)
    msg+=" "
    msg+=$(printf '%.1f' $(bc -l <<< "($curr / $full) * 100"))
    msg+="%%"

    echo $msg
}

wifi() {
    state=$(cat /sys/class/net/wlo1/operstate)
    ssid=$(iwgetid -r)
    msg=""

    if [[ $state == "up" ]]; then
        msg="$ssid"
    else
        msg="Disconnected"
    fi

    echo $msg
}

while true; do
    buf=""

    buf+="%{c}"
    buf+="$(desktops)"
    buf+="%{r}"

    if [[ -d /sys/class/net/wlo1/ ]]; then
        buf+="$(wifi) | "
    fi

    if [[ -d /sys/class/power_supply/BAT0/ ]]; then
        buf+="$(battery) | "
    fi

    buf+="$(clock)"

    echo $buf
    sleep 1
done
