#!/bin/zsh

. panel-settings

hi="%{F$COLOUR_HI}"
ul="%{U$COLOUR_HI}"

clock() {
    date +"%d/%m/%Y %H:%M"
}

desktops() {
    desktops=""

    for monitor in $(bspc query -M); do
        desktops+="${hi}[ %{F-}"

        for desktop in $(bspc query -D -m $monitor); do
            if [[ $desktop -eq $(bspc query -D -d focused) ]]; then
                desktops+="$hi$ul$desktop%{F-U-} "
            else
                desktops+="$desktop "
            fi
        done

        desktops="${desktops%?}$hi ]%{F-}"
    done

    echo "$desktops"
}

while true; do
    buf=""

    # buf="$buf $(music)"
    buf+="%{c}"
    buf+="$(desktops)"
    buf+="%{r}"
    # buf+= "$buf $(apps)"
    # buf+= "$buf $green$fg $(batt)%"
    # buf+= "$buf $blue$fg $(vol)"
    buf+="$(clock) "

    echo $buf
    sleep 1
done
